### ISSUE TITLE
Customize index name when using two OKD's cluster sharing one ELK stack

### ISSUE THREAD

**Issue by uselessidbr** [ViaQ/fluent-plugin-viaq_data_model#29]
I'm running two OKD's 3.11 clusters and our company decided to externalize the logs to an external EFK stack. We're still using FLUENTD internally.

The problem is, i couldn't find how to customize the indices's names so we can differentiate the logs from both OKD's clusters.

It seems that the "operations" and "project" indices are somehow "hardcoded".

AFAIK it's being handled by VIAQ plugin and i couldn't find any way to surpass this.

Sadly i don't know much about how EFK stack setup works.

Hope someone can elucidate it.

Thanks in advance!

**Comment by richm** [comment]
The only supported way to send logs to an external logger in OKD 3.11 https://docs.okd.io/3.11/install_config/aggregate_logging.html#aggregated-fluentd - "Configuring Fluentd to Send Logs to an External Log Aggregator"

**Comment by uselessidbr** [comment]
> The only supported way to send logs to an external logger in OKD 3.11 https://docs.okd.io/3.11/install_config/aggregate_logging.html#aggregated-fluentd - "Configuring Fluentd to Send Logs to an External Log Aggregator"

That's exactly what i did and it's working. The question is, as i have two clusters sending logs, the indices's names are the same for both clusters. How can i differentitate both? 

I need to customize the index name, per example:  "operations" like: 

1) operations.cluster1;
2) operations.cluster2.

**Comment by richm** [comment]
> That's exactly what i did and it's working

I suggest asking on users@lists.openshift.redhat.com
